### ISSUE TITLE
依存バージョンの指定がゆるすぎる

### ISSUE THREAD

**Issue by KisaragiEffective** [approvers/rusty-ponyo#31]
`cargo +nightly update -Z minimal-versions && cargo check`すると壊れる。

解決方法：
* バージョンをpatchまで指定する

**Comment by kawaemon** [comment]
壊れるのはこちらのバージョン指定が緩すぎるからではありません。

**Comment by kawaemon** [comment]
https://github.com/approvers/rusty-ponyo/compare/dep-min
