### ISSUE TITLE
限界ポイント Formula v3 の実装

### ISSUE THREAD

**Issue by m1sk9** [approvers/rusty-ponyo#79]

**Comment by nanai10a** [comment]
@kawaemon 暫定的に "v3" として実装を試みますが, 限界で話に挙がった "nanai-v1" のような名前付けに後から変更してもらっても構いません. というか, そうするならそう言ってもらえれば対応します.

**Comment by kawaemon** [comment]
v3 で問題ありません！
限界ポイント初の真面目に考えられた関数なので、正式にデフォルト扱いでいいと思います
